### ISSUE TITLE
ATP Rankings : Ranking data missing for these players

### ISSUE THREAD

**Issue by bazzaar** [JeffSackmann/tennis_atp#109] opened 2019-05-26 15:01 UTC
Hi,

As of commit `fe99318`, these players do not have any rankings data in this repository : 

|   id   |   fname    |   lname   | hand |    dob     | country |    issue     |
|--------|------------|-----------|------|------------|---------|--------------|
|   ?    | Paul       | Podbury   | R    | 1979-03-13 | AUS     | #102         |
|   ?    | Dante      | Cipulli   | R    | 1981-11-11 | ARG     | #101         |
|   ?    | Pedro      | Ast       | R    | 1988-08-12 | VEN     | #100         |
|   ?    | Michael    | Schneider | R    | 1985-02-20 | GER     | #98          |
|   ?    | Kostyantyn | Dmytrenko | R    | 1978-01-21 | UKR     | #94          |
|   ?    | Jonathan   | Russo     | R    | 1984-06-02 | USA     | #93          |
|   ?    | Robert     | Kowalczyk | R    | 1980-10-23 | USA     | #91          |
|   ?    | Pedro      | Campos    | R    | 1986-08-16 | BRA     | #90          |
|   ?    | Francesco  | Forti     | R    | 1999-07-26 | ITA     | #89          |
| 111465 | Stearns    | B.J.      | U    | 1976-04-26 | USA     | #96          |
| 123461 | Prudhomme  | Gregg     | U    | 1970-06-24 | USA     | #92          |
| 117508 | Tribler    | Jan Axel  | U    | 1978-03-10 | DEN     | #95,#99,#103 |
| 117700 | Srinavasan | P.K.      | U    | 1978-08-05 | IND     | #97          |

Hope this helps.
bazzaar

**Comment by JeffSackmann** [comment] 2020-01-29 17:38
the latest commit resolves issue #14, which overlapped with this one. Rankings should be fixed for most of these players. The remaining ones are Forti, Stearns, Tribler, and Srinavasan.

**Comment by JeffSackmann** [comment] 2020-01-29 21:02
BJ Stearns is a dupe of William Stearns (117991), and his results and ranking data are now in the repo under William's ID.

Tribler and Srinavasan are fixed.

Forti was incorrectly merged with Federico Iannaccone (200713), and that's now fixed, both in rankings and results. 2020 results are still merged, but will be fixed with the next update of 2020 results, after the AO.

**Closed by JeffSackmann** 2020-01-29 21:02 UTC
