### ISSUE TITLE
ATP players : Advanced age at end of [rankings] career may indicate data issue.

### ISSUE THREAD

**Issue by bazzaar** [JeffSackmann/tennis_atp#87] opened 2018-12-08 20:37 UTC
Hi,
Some players have an advanced age at the end of their spell in the rankings, and while this may be accurate in some of the highlighted cases, it may indicate issues with dob, or even players sharing the same ATP id.

|   id  |     fname      |      lname      | hand |    dob     | country | rank_begin |  rank_end  | rankdays |     age_rank_begin       |      age_rank_end        |
|--------|----------------|-----------------|------|------------|---------|------------|------------|----------|--------------------------|--------------------------|
| 100092 | Alex           | Metreveli       | R    | 1944-11-02 | RUS     | 1973-08-23 | 2011-07-25 |    13850 | 28 years 9 mons 21 days  | 66 years 8 mons 23 days  |
| 100001 | Gardnar        | Mulloy          | R    | 1913-11-22 | USA     | 1977-07-02 | 1978-01-16 |      198 | 63 years 7 mons 10 days  | 64 years 1 mon 24 days   |
| 111043 | Sung Bae       | Kim             | U    | 1948-10-10 | KOR     | 2010-07-12 | 2010-07-12 |        0 | 61 years 9 mons 2 days   | 61 years 9 mons 2 days   |
| 100415 | Michael        | Grant           | R    | 1956-02-03 | USA     | 1977-12-31 | 2017-07-10 |    14436 | 21 years 10 mons 28 days | 61 years 5 mons 7 days   |
| 100193 | Wanaro         | Ngodrella       | R    | 1949-10-19 | FRA     | 1973-08-23 | 2008-01-07 |    12555 | 23 years 10 mons 4 days  | 58 years 2 mons 19 days  |
| 106440 | Abdel          | Aslam Mahmoudi  | R    | 1935-12-30 | ALG     | 1991-11-11 | 1992-11-02 |      357 | 55 years 10 mons 12 days | 56 years 10 mons 3 days  |
| 100183 | Jim            | Ward            | R    | 1949-07-28 | USA     | 1979-12-26 | 2005-09-12 |     9392 | 30 years 4 mons 29 days  | 56 years 1 mon 15 days   |
| 100149 | Toshiro        | Sakai           | R    | 1947-11-23 | JPN     | 1973-08-23 | 2003-08-18 |    10952 | 25 years 9 mons          | 55 years 8 mons 25 days  |
| 100009 | Istvan         | Gulyas          | R    | 1931-10-14 | HUN     | 1973-09-13 | 1987-05-25 |     5002 | 41 years 10 mons 30 days | 55 years 7 mons 11 days  |
| 100015 | Sammy          | Giammalva       | R    | 1934-08-01 | USA     | 1989-07-10 | 1989-08-14 |       35 | 54 years 11 mons 9 days  | 55 years 13 days         |
| 100019 | Wieslaw        | Gasiorek        | R    | 1936-01-13 | POL     | 1990-11-05 | 1990-11-26 |       21 | 54 years 9 mons 23 days  | 54 years 10 mons 13 days |
| 100002 | Pancho         | Segura          | R    | 1921-06-20 | ECU     | 1975-03-05 | 1975-12-15 |      285 | 53 years 8 mons 15 days  | 54 years 5 mons 25 days  |
| 100115 | Jaime          | Fillol          | R    | 1946-06-03 | CHI     | 1973-08-23 | 1999-10-04 |     9538 | 27 years 2 mons 20 days  | 53 years 4 mons 1 day    |
| 100236 | John           | James           | R    | 1951-03-07 | AUS     | 1974-06-03 | 2003-10-13 |    10724 | 23 years 2 mons 27 days  | 52 years 7 mons 6 days   |
| 100003 | Frank          | Sedgman         | R    | 1927-10-02 | AUS     | 1974-06-03 | 1979-12-26 |     2032 | 46 years 8 mons 1 day    | 52 years 2 mons 24 days  |
| 112312 | Frank Arthur   | Sedgman         |      | 1927-10-29 | AUS     | 1974-08-09 | 1978-12-31 |     1605 | 46 years 9 mons 11 days  | 51 years 2 mons 2 days   |
| 100070 | Jan            | Kukal           | R    | 1942-09-13 | CZE     | 1973-08-23 | 1993-11-15 |     7389 | 30 years 11 mons 10 days | 51 years 2 mons 2 days   |
| 100064 | Juan           | Gisbert         | R    | 1942-04-05 | ESP     | 1973-08-23 | 1992-09-07 |     6955 | 31 years 4 mons 18 days  | 50 years 5 mons 2 days   |
| 100010 | Luis           | Ayala           | R    | 1932-09-18 | CHI     | 1980-12-22 | 1983-01-03 |      742 | 48 years 3 mons 4 days   | 50 years 3 mons 15 days  |
| 100006 | Grant          | Golden          | R    | 1929-08-21 | USA     | 1978-07-12 | 1978-12-31 |      172 | 48 years 10 mons 22 days | 49 years 4 mons 10 days  |
| 101339 | Agustin        | Moreno          | R    | 1967-03-31 | MEX     | 1985-05-06 | 2016-06-27 |    11375 | 18 years 1 mon 6 days    | 49 years 2 mons 27 days  |
| 100008 | Kurt           | Nielsen         | R    | 1930-11-19 | DEN     | 1979-12-26 | 1979-12-26 |        0 | 49 years 1 mon 7 days    | 49 years 1 mon 7 days    |
| 100022 | Roy            | Emerson         | R    | 1936-11-03 | AUS     | 1973-08-23 | 1984-06-25 |     3959 | 36 years 9 mons 20 days  | 47 years 7 mons 22 days  |
| 101389 | Oren           | Motevassel      | L    | 1967-08-26 | USA     | 1985-10-21 | 2015-03-23 |    10745 | 18 years 1 mon 26 days   | 47 years 6 mons 28 days  |
| 100642 | Juan Carlos    | Yunis           | R    | 1960-01-17 | ARG     | 1980-12-22 | 2007-01-22 |     9527 | 20 years 11 mons 5 days  | 47 years 5 days          |
| 100005 | Richard Pancho | Gonzales        | R    | 1928-05-09 | USA     | 1973-08-23 | 1975-04-30 |      615 | 45 years 3 mons 14 days  | 46 years 11 mons 21 days |
| 100020 | Alejandro      | Olmedo          | R    | 1936-03-24 | PER     | 1973-09-26 | 1983-01-03 |     3386 | 37 years 6 mons 2 days   | 46 years 9 mons 10 days  |
| 100004 | Giuseppe       | Merlo           | R    | 1927-10-11 | ITA     | 1973-09-13 | 1974-05-01 |      230 | 45 years 11 mons 2 days  | 46 years 6 mons 21 days  |
| 101962 | Younes         | El Aynaoui      | R    | 1971-09-12 | MAR     | 1990-03-12 | 2018-03-19 |    10234 | 18 years 6 mons          | 46 years 6 mons 7 days   |
| 100273 | Kim            | Warwick         | R    | 1952-04-08 | AUS     | 1973-08-23 | 1998-06-29 |     9076 | 21 years 4 mons 15 days  | 46 years 2 mons 21 days  |
| 100113 | Jan            | Kodes           | R    | 1946-03-01 | CZE     | 1973-08-23 | 1992-05-18 |     6843 | 27 years 5 mons 22 days  | 46 years 2 mons 17 days  |
| 100016 | Ken            | Rosewall        | R    | 1934-11-02 | AUS     | 1973-08-23 | 1980-12-22 |     2678 | 38 years 9 mons 21 days  | 46 years 1 mon 20 days   |
| 100041 | Ned            | Neely           | R    | 1940-01-14 | USA     | 1985-08-12 | 1985-10-28 |       77 | 45 years 6 mons 29 days  | 45 years 9 mons 14 days  |
| 100428 | Gene           | Mayer           | R    | 1956-04-11 | USA     | 1975-03-05 | 2002-01-21 |     9819 | 18 years 10 mons 24 days | 45 years 9 mons 10 days  |
| 100474 | Chris          | Lewis Nzl       | R    | 1957-03-09 | NZL     | 1974-12-20 | 2002-11-25 |    10202 | 17 years 9 mons 11 days  | 45 years 8 mons 16 days  |
| 100038 | Jaime          | Pinto Bravo     | R    | 1939-10-09 | CHI     | 1973-08-23 | 1985-02-25 |     4204 | 33 years 10 mons 14 days | 45 years 4 mons 16 days  |
| 117703 | George         | Barth           | U    | 1969-05-19 | USA     | 1992-11-02 | 2014-09-29 |     8001 | 23 years 5 mons 14 days  | 45 years 4 mons 10 days  |
| 102033 | Abdelhak       | Hameurlaine     | R    | 1972-03-19 | ALG     | 1990-11-12 | 2017-05-29 |     9695 | 18 years 7 mons 24 days  | 45 years 2 mons 10 days  |

These are players who [currently in this repo] are given as over 45 years old when they finally dropped from the rankings list. The careers of some of the players in this list likely partly preceded the oldest ranking data for them currently in the database. I'll verify the data for all these players, and either remove them from this list, or describe the problem to be fixed.

I notice already that Frank Sedgman appears twice in the list, with different id's, maybe two different players, but probably unlikely, I think.

bazzaar

**Comment by JeffSackmann** [comment] 2020-01-30 16:16
the following players were fixed:

100092 | Alex | Metreveli
100415 | Michael | Grant
100193 | Wanaro | Ngodrella
100015 | Sammy | Giammalva
100115 | Jaime | Fillol
100064 | Juan | Gisbert
101339 | Agustin | Moreno

Sedgman 112312 is a dupe of the other, and fixed

the following players are correct, which usually means that I found a match result for the (old) player corresponding with the ranking data:

100001 | Gardnar | Mulloy
100149 | Toshiro | Sakai
100009 | Istvan | Gulyas
100019 | Wieslaw | Gasiorek
100002 | Pancho | Segura
100003 | Frank | Sedgman
100070 | Jan | Kukal
100010 | Luis | Ayala
100022 | Roy | Emerson
101389 | Oren | Motevassel
100005 | Richard Pancho | Gonzales
100004 | Giuseppe | Merlo
101962 | Younes | El Aynaoui
100016 | Ken | Rosewall
100428 | Gene | Mayer
100038 | Jaime | Pinto Bravo
117703 | George | Barth
102033 | Abdelhak | Hameurlaine

The following are correct per the ATP site, though I am varying degrees of doubtful. They have no match results that correspond with the late ranking data, but the ranking data is associated with the DOB. Since the ATP does not have all match results (especially Satellite circuits from the 90s, and occasional other tournaments before that), this doesn't necessarily mean that the ranking data is wrong.


111043 | Sung Bae | Kim
106440 | Abdel | Aslam Mahmoudi
100183 | Jim | Ward
100236 | John | James
100006 | Grant | Golden
100008 | Kurt | Nielsen
100642 | Juan Carlos | Yunis
100020 | Alejandro | Olmedo
100273 | Kim | Warwick
100113 | Jan | Kodes
100041 | Ned | Neely
100474 | Chris | Lewis Nzl

**Closed by JeffSackmann** 2020-01-30 16:16 UTC
